# Copyright 2023 The OpenVEX Authors
# SPDX-License-Identifier: Apache-2.0

name: ci-build-test

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  build:
    name: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v2.2.0
        with:
          go-version: '1.23'
          check-latest: true
          cache: true

      - name: build
        run: make vex

  test:
    name: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0

      - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v2.2.0
        with:
          go-version: '1.23'
          check-latest: true
          cache: true

      - name: test
        run: make test
